In [1]:
import numpy as np
import pandas as pd

The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [3]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
print(x+1 )

[ 2  3  4  5  6  7  8  9 10 11]


Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself

In [9]:
a =[]
for i in range(0,10):
  for j in range(0,10):
    a.append(i+j);
b = np.array(a).reshape(10,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance.
a. First, create a fake “data set” with 50 examples, each with five dimensions.
b. import numpy.random as npr data = np.exp ( npr.randn(50, 5) )
c. Don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number
generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal distribution.

In [12]:
import numpy as np
import numpy.random as npr
data = np.exp(npr.randn(50,5))
data

array([[ 0.39026213,  1.97709091,  0.85393625,  0.77595947,  1.46307768],
       [ 1.04356842,  1.75070679,  0.74577233,  2.33177223,  1.19059436],
       [ 0.69472763,  2.02132509,  1.21350836,  0.29904535,  0.11335324],
       [ 3.5459432 ,  1.53626347,  7.80487738,  2.72833001,  3.108939  ],
       [ 0.5172653 ,  1.92544835,  1.07034295,  2.96689654,  1.23201394],
       [ 1.11984794,  4.53348307,  2.32463775,  2.00264102,  4.68494728],
       [ 1.99023718,  2.0347166 ,  0.90646617,  1.79331147,  3.13558222],
       [ 2.41818464,  2.52673215,  1.34170585,  1.92864477,  4.30268939],
       [ 1.12711159,  2.36896397,  1.12086491,  1.43373855,  0.6898912 ],
       [ 4.47524892,  3.14825675,  0.38790281,  2.54083041,  4.58610642],
       [ 4.51222642,  4.50084467,  0.78673263,  0.22806918,  0.44416094],
       [ 0.56094722,  1.19613188,  0.70819527,  0.16265045,  8.87476541],
       [ 0.33069251,  0.17816588,  1.16284463,  0.85528517,  0.81185015],
       [ 0.62983523,  1.34048678,  2.6

Now, compute the mean and standard deviation of each column. This should result in two vectors of length, You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.

In [22]:
mean=[]
std=[]
for i in range(0,5):
  mean.append(np.mean(data[:,i]))
  std.append(np.std(data[:,i]))
mean = np.array(mean)
std= np.array(std)
print(mean)
print(std)

[1.5983787  1.53407964 1.38822056 1.63058069 1.73156596]
[1.69729229 1.34635332 1.37308882 1.37612951 2.04797497]


In [16]:
arr = np.concatenate([mean,std])
final_arr = np.reshape(arr,(2,5))
print(final_arr)
print(final_arr.ndim)

[[1.5983787  1.53407964 1.38822056 1.63058069 1.73156596]
 [1.69729229 1.34635332 1.37308882 1.37612951 2.04797497]]
2


Now standardize the data matrix by
1) subtracting the mean of each column
2) dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out

In [24]:
sub = []
for i in range(0,50):
    for j in range(0,5):
        sub.append(data[i,j] - mean[j])
mean_1 = np.array(sub).reshape(50,5)
mean_1

array([[-1.20811657e+00,  4.43011272e-01, -5.34284315e-01,
        -8.54621218e-01, -2.68488278e-01],
       [-5.54810284e-01,  2.16627159e-01, -6.42448237e-01,
         7.01191538e-01, -5.40971602e-01],
       [-9.03651067e-01,  4.87245451e-01, -1.74712201e-01,
        -1.33153533e+00, -1.61821273e+00],
       [ 1.94756450e+00,  2.18383406e-03,  6.41665682e+00,
         1.09774932e+00,  1.37737303e+00],
       [-1.08111340e+00,  3.91368716e-01, -3.17877616e-01,
         1.33631585e+00, -4.99552027e-01],
       [-4.78530756e-01,  2.99940344e+00,  9.36417190e-01,
         3.72060330e-01,  2.95338132e+00],
       [ 3.91858479e-01,  5.00636963e-01, -4.81754392e-01,
         1.62730785e-01,  1.40401626e+00],
       [ 8.19805940e-01,  9.92652517e-01, -4.65147153e-02,
         2.98064084e-01,  2.57112343e+00],
       [-4.71267110e-01,  8.34884330e-01, -2.67355658e-01,
        -1.96842140e-01, -1.04167476e+00],
       [ 2.87687022e+00,  1.61417711e+00, -1.00031776e+00,
         9.10249718e-01

In [25]:
mean_1.shape

(50, 5)

In [28]:
div = []
for i in range(0,50):
    for j in range(0,5):
        div.append(data[i,j] / std[j])
nor = np.array(div).reshape(50,5)
nor

array([[0.22993219, 1.4684785 , 0.62190897, 0.56387096, 0.71440213],
       [0.61484308, 1.30033236, 0.5431348 , 1.69444243, 0.58135201],
       [0.40931526, 1.50133331, 0.88377994, 0.21730902, 0.05534894],
       [2.08917653, 1.14105521, 5.68417516, 1.98261137, 1.51805517],
       [0.30475912, 1.43012114, 0.77951472, 2.15597189, 0.60157666],
       [0.65978497, 3.36723132, 1.69299882, 1.45527075, 2.28759988],
       [1.17259543, 1.51127982, 0.66016572, 1.30315603, 1.53106472],
       [1.42473083, 1.87672293, 0.97714425, 1.40149947, 2.10094823],
       [0.66406452, 1.75954107, 0.8163091 , 1.04186309, 0.33686506],
       [2.63669903, 2.33835851, 0.2825038 , 1.84635995, 2.23933715],
       [2.6584852 , 3.34298924, 0.57296558, 0.16573235, 0.21687811],
       [0.33049536, 0.88842346, 0.515768  , 0.11819415, 4.33343451],
       [0.19483534, 0.13233218, 0.84688231, 0.62151503, 0.39641605],
       [0.37108236, 0.99564265, 1.94271402, 0.445795  , 0.81009542],
       [0.49337689, 2.53778276, 0.

In [29]:
nor.shape

(50, 5)

In [31]:
mean = []
std = []
for i in range(0,5):
    mean.append(np.mean(nor[:,i]))
    std.append(np.std(nor[:,i]))
mean = np.array(mean)
std = np.array(std)
print(mean)
print(std)

[0.94172272 1.13943317 1.01102022 1.18490351 0.84550153]
[1. 1. 1. 1. 1.]
